In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:

dataset = pd.read_csv('heart_disease.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:

print(x[1])

[69.0 'Female' 146.0 286.0 'High' 'No' 'Yes' 'Yes' 25.2217985244363 'No'
 'Yes' 'No' 'Medium' 'High' 8.744033968961478 'Medium' 133.0 157.0
 9.355389404894291 19.298875477603804]


In [3]:
print(y)

['No' 'No' 'No' ... 'Yes' 'Yes' 'Yes']


#Data Preprocessing:
Label Encoding

In [4]:

from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder() 
le2 = LabelEncoder() 
le6 = LabelEncoder() 
le8 = LabelEncoder() 
le10 = LabelEncoder() 
x[:,1] = le1.fit_transform(x[:,1])
x[:,2] = le2.fit_transform(x[:,2])
x[:,6] = le6.fit_transform(x[:,6])
x[:,8] = le8.fit_transform(x[:,8])
x[:,10] = le10.fit_transform(x[:,10])

In [5]:
print(x)

[[56.0 1 33 ... nan 12.969245689269126 12.387250402785936]
 [69.0 0 26 ... 157.0 9.355389404894291 19.298875477603804]
 [46.0 1 6 ... 92.0 12.70987253489807 11.230925676461878]
 ...
 [73.0 1 32 ... 88.0 4.408867005635261 9.492429009585337]
 [23.0 1 22 ... 153.0 7.215633937566714 11.873485847080852]
 [38.0 0 8 ... 149.0 14.387809821615413 6.208531153622675]]


In [6]:
print(y)

['No' 'No' 'No' ... 'Yes' 'Yes' 'Yes']


In [7]:

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
!pip install liac-arff -q # cài thư viện arff nếu chưa có

import arff
df = pd.read_csv('heart_disease.csv')

# 5 cột categorical cần encode (theo code cũ của bạn)
df.iloc[:,1]  = LabelEncoder().fit_transform(df.iloc[:,1])
df.iloc[:,2]  = LabelEncoder().fit_transform(df.iloc[:,2])
df.iloc[:,6]  = LabelEncoder().fit_transform(df.iloc[:,6])
df.iloc[:,8]  = LabelEncoder().fit_transform(df.iloc[:,8])
df.iloc[:,10] = LabelEncoder().fit_transform(df.iloc[:,10])

# Tạo attributes cho ARFF
attributes = []
for col in df.columns:
    if df[col].dtype == 'object' and col != df.columns[-1]:  
        attributes.append((col, 'NUMERIC'))  
    elif df[col].dtype == 'object':  
        attributes.append((col, sorted(df[col].unique().tolist())))
    else:
        attributes.append((col, 'NUMERIC'))

# Xuất file .arff
with open('heart_disease_preprocessed.arff', 'w', encoding='utf-8') as f:
    arff.dump({
        'relation': 'heart_disease',
        'attributes': attributes,
        'data': df.replace({np.nan: None}).values.tolist()
    }, f)

!dir *.arff #dùng windows
# !ls -la *.arff #dùng linux or mac

ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^


 Volume in drive C is Windows
 Volume Serial Number is 7C12-2700

 Directory of c:\Users\VUTHANHHUNG\Documents\GitHub\Data-Mining-Project

23/11/2025  03:44 PM         1,336,936 heart_disease_preprocessed.arff

 Directory of c:\Users\VUTHANHHUNG\Documents\GitHub\Data-Mining-Project


 Directory of c:\Users\VUTHANHHUNG\Documents\GitHub\Data-Mining-Project

               1 File(s)      1,336,936 bytes
               0 Dir(s)  19,043,450,880 bytes free
